# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Jekyll app to Azure Web App - hmis-jeb419

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # 1. Configuramos Ruby en lugar de Node.js
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Versión de Ruby compatible con Jekyll
          bundler-cache: true # Acelera la instalación cacheando las gemas

      # 2. Instalamos dependencias y compilamos Jekyll forzando el baseurl vacío
      - name: Build Jekyll site
        run: |
          bundle install
          bundle exec jekyll build --baseurl ""

      # 3. Subimos SOLO la carpeta compilada (_site)
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-app
          path: _site/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: jekyll-app
          path: .
       
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40550AAF2FCC4FB9AB0E223D62856868 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2470E052CE58492B8CCAB1003D80370E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4FBF2DACBC8480AB5054342850DE772 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hmis-jeb419'
          slot-name: 'Production'
          package: .
